### PR TITLE
Fix Review Form Field Reset

### LINKED ISSUE #234: fix autosave form reset issue

### PR DESCRIPTION
**Pull request by hunterchen7**
closes #234

### CODE REVIEW

File: src/pages/internal/review.tsx [hunk 1]
```diff
@@ -53,14 +53,26 @@ const Review = () => {
...
+  }, [applicantId]);
+
+  // on review data change (new review), reset form with new data
+  // this fills in the applicant and reviewer IDs that get reset by the previous effect
+  useEffect(() => {
+    if (reviewIsFetched && reviewData) {
+      form.reset(reviewData);
     }
-  }, [applicantId, reviewData, form]);
+    // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (basokant) [inline src/pages/internal/review.tsx:74]: yikes

**Review by basokant — APPROVED** [review]
lgtm
